/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-10-15 18:17:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chitiet_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Calendar</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap/css/bootstrap.min.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap/js/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"datepick/moment.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"datepick/bootstrap-datetimepicker.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"datepick/vi.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link \trel=\"stylesheet\" type=\"text/css\" href=\"datepick/bootstrap-datetimepicker.min.css\">\r\n");
      out.write("\t<!-- Angular validation -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"angular-validate/font-awesome-4.6.3/css/font-awesome.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"angular-validate/angular.min.js\"></script>\r\n");
      out.write("\t<!-- Customize -->\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"bootstrap/Css.css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"bootstrap/js.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    \t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t<div class=\"panel panel-chitiet\">\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"active\" id=\"chitiet-form-link\">Chi Tiết</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-xs-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" id=\"khachmoi-form-link\">Khách Mời</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-12\" ng-app=\"demoApp\" ng-controller=\"RegisterCtrl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form id=\"chitiet-form\" method=\"post\" style=\"display:block;\" name=\"form\" ng-submit=\"register()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t                        \t<div class=\"row\">\r\n");
      out.write("\t\t\t                        \t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"><label class=\"control-label lb\">Tên Sự Kiện</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" name=\"tensukien\" ng-model=\"tensukien\" type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Tên sự kiện\" ng-pattern=\"/^[a-zA-Z 0-9]+$/\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-check text-success\" ng-show=\"form.tensukien.$dirty && form.tensukien.$valid\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div ng-show=\"form.tensukien.$dirty && form.tensukien.$invalid\" class=\"text-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span ng-show=\"form.tensukien.$error.required\">Tên Sự Kiện không được bỏ trống</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span ng-show=\"form.tensukien.$error.pattern\">Chỉ bao gồm các kí tự a-z 0-9</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t                        \t<div class=\"row\">\r\n");
      out.write("\t\t\t                        \t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"><label class=\"control-label lb\">Địa Điểm</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" name=\"diadiem\" ng-model=\"diadiem\" type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Địa điểm\" ng-pattern=\"/^[a-zA-Z 0-9]+$/\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-check text-success\" ng-show=\"form.diadiem.$dirty && form.diadiem.$valid\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div ng-show=\"form.diadiem.$dirty && form.diadiem.$invalid\" class=\"text-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span ng-show=\"form.diadiem.$error.required\">Địa điểm không được bỏ trống</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span ng-show=\"form.diadiem.$error.pattern\">Chỉ bao gồm các kí tự a-z 0-9</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"htnhac\" class=\"control-label lb\">ThờiGian</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\" col-md-5 col-md-offset-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin-bottom: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    <div class='input-group date' id='datetimepicker6'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        <input type='text' class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        <span class=\"input-group-addon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t             <span class=\"glyphicon glyphicon-calendar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"margin-bottom: 0;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    <div class='input-group date' id='datetimepicker7'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        <input type='text' class=\"form-control\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        <span class=\"input-group-addon\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t            <span class=\"glyphicon glyphicon-calendar\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t        </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"><label for=\"htnhac\" class=\"control-label lb\">Chế Độ Nhắc</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t                              <button type=\"button\" class=\"btn btn-default\">Một Lần</button>\r\n");
      out.write("\t\t\t\t\t\t                              <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t                                <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t                                <span class=\"sr-only\">Toggle Dropdown</span>\r\n");
      out.write("\t\t\t\t\t\t                              </button>\r\n");
      out.write("\t\t\t\t\t\t                              <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t                                <li><a href=\"#\">Một Lần</a></li>\r\n");
      out.write("\t\t\t\t\t\t                                <li><a href=\"#\">Lặp</a></li>\r\n");
      out.write("\t\t\t\t\t\t                              </ul>\r\n");
      out.write("\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t                            </div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"><label for=\"htnhac\" class=\"control-label lb\">Hình thức Lặp</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t                              <button type=\"button\" class=\"btn btn-default\">Mỗi Ngày</button>\r\n");
      out.write("\t\t\t\t\t\t                              <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t                                <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t                                <span class=\"sr-only\">Toggle Dropdown</span>\r\n");
      out.write("\t\t\t\t\t\t                              </button>\r\n");
      out.write("\t\t\t\t\t\t                              <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t                                <li><a href=\"#\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t                                <li><a href=\"#\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t                              </ul>\r\n");
      out.write("\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t                            </div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"><label for=\"htnhac\" class=\"control-label lb\">Hình thức nhắc</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t\t                              <button type=\"button\" class=\"btn btn-default\">Email</button>\r\n");
      out.write("\t\t\t\t\t\t                              <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t\t                                <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t                                <span class=\"sr-only\">Toggle Dropdown</span>\r\n");
      out.write("\t\t\t\t\t\t                              </button>\r\n");
      out.write("\t\t\t\t\t\t                              <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t                                <li><a href=\"#\">Email</a></li>\r\n");
      out.write("\t\t\t\t\t\t                                <li><a href=\"#\">Số Điện Thoại</a></li>\r\n");
      out.write("\t\t\t\t\t\t                              </ul>\r\n");
      out.write("\t\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t                            </div>\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t                        \t<div class=\"row\">\r\n");
      out.write("\t\t\t                        \t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"><label class=\"control-label lb\">Lời Nhắc</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" name=\"loinhac\" ng-model=\"loinhac\" type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Lời Nhắc\" ng-pattern=\"/^[a-zA-Z 0-9]+$/\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-check text-success\" ng-show=\"form.loinhac.$dirty && form.loinhac.$valid\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div ng-show=\"form.loinhac.$dirty && form.loinhac.$invalid\" class=\"text-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span ng-show=\"form.loinhac.$error.required\">Lời Nhắc không được bỏ trống</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span ng-show=\"form.loinhac.$error.pattern\">Chỉ bao gồm các kí tự a-z 0-9</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t                        <div class=\"form-group\">\r\n");
      out.write("\t\t\t                        \t<div class=\"row\">\r\n");
      out.write("\t\t\t                        \t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"><label class=\"control-label lb\">Ghi chú</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" name=\"ghichu\" ng-model=\"ghichu\" type=\"text\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Ghi Chú\" ng-pattern=\"/^[a-zA-Z 0-9]+$/\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-check text-success\" ng-show=\"form.ghichu.$dirty && form.ghichu.$valid\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div ng-show=\"form.ghichu.$dirty && form.ghichu.$invalid\" class=\"text-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span ng-show=\"form.ghichu.$error.pattern\">Chỉ bao gồm các kí tự a-z 0-9</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"chitiet-submit\" id=\"chitiet-submit\" tabindex=\"4\" class=\"form-control btn btn-chitiet\" value=\"Chỉnh Sửa\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form id=\"khachmoi-form\" method=\"post\" role=\"form\" style=\"display: none;\" name=\"form2\" ng-submit=\"register()\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t                        \t<div class=\"row\">\r\n");
      out.write("\t\t\t                        \t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\"><label class=\"control-label lb\">Email</label></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input class=\"form-control\" name=\"email\" ng-model=\"email\" type=\"email\" placeholder=\"Email\" required>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-check text-success\" ng-show=\"form2.email.$dirty && form2.email.$valid\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div ng-show=\"form2.email.$dirty && form2.email.$invalid\" class=\"text-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times text-danger\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span ng-show=\"form2.email.$error.required\">Ban chưa nhập địa chỉ email</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span ng-show=\"form2.email.$error.email\">Không đúng định dạng email</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"submit\" name=\"khachmoi-submit\" id=\"khachmoi-submit\" tabindex=\"4\" class=\"form-control btn btn-khachmoi\" value=\"Thêm\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
